name: Ruby

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: "./"
        name: "Without Gemfile"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: "./"
        name: "With Gemfile"
        with:
          gemfile: "test/Gemfile"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
